language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
# command to run tests
script:
  - export TOKEN=$TOKEN
  - export CHAT_ID=$CHAT_ID
  - pytest